# Generated by Django 5.0.6 on 2024-07-30 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cartitem_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='back_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shirts/'),
            preserve_default=False,
        ),
    ]
