# Generated by Django 5.0.6 on 2024-08-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='shirt',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_stock', models.PositiveIntegerField(default=0)),
                ('medium_stock', models.PositiveIntegerField(default=0)),
                ('large_stock', models.PositiveIntegerField(default=0)),
                ('extra_large_stock', models.PositiveIntegerField(default=0)),
                ('shirt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.shirt')),
            ],
        ),
    ]
