# Generated by Django 5.0.6 on 2024-08-05 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_shirt_sizes_alter_shirt_stock_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='stock',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='extra_large_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shirt',
            name='large_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shirt',
            name='medium_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shirt',
            name='small_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
